# Generated by Django 4.2.6 on 2024-02-28 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='post',
            name='post_author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
