# Generated by Django 4.2.6 on 2024-05-02 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_completed',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_streak',
            field=models.IntegerField(default=0),
        ),
    ]
