# Generated by Django 4.2.6 on 2024-05-02 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_profile_current_streak_profile_last_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_completed',
            field=models.DateTimeField(default=datetime.date(2024, 5, 1)),
        ),
    ]
