# Generated by Django 4.2.6 on 2024-05-10 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_profile_location_alter_profile_last_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='positivity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_completed',
            field=models.DateTimeField(default=datetime.date(2024, 5, 9)),
        ),
    ]
