# Generated by Django 4.2.6 on 2024-05-28 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_profile_last_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_completed',
            field=models.DateTimeField(default=datetime.date(2024, 5, 27)),
        ),
    ]
