# Generated by Django 4.2.6 on 2024-06-05 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_profile_last_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_completed',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 4, 0, 47, 20, 603107, tzinfo=datetime.timezone.utc)),
        ),
    ]
