# Generated by Django 4.2.6 on 2024-06-06 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_profile_last_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_completed',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 0, 44, 30, 13640, tzinfo=datetime.timezone.utc)),
        ),
    ]
